Employee.create!([
  {first_name: "Евгений",
   last_name: "Исайченко",
   patronymic: "Андреевич",
   mobile_phone1: "380992889884",
   mobile_phone2: "",
   ip_phone: "115",
   email: "admin@dolina.ua",
   birthday: "11.05.1985",
   position: "Системный администратор",
   avatar: "25950734.jpeg",
   department: "IT"},
  {first_name: "Вячеслав",
   last_name: "Сергиенко",
   patronymic: "Анатольевич",
   mobile_phone1: "380992959018",
   mobile_phone2: "",
   ip_phone: "116",
   email: "sva0709@rambler.ru",
   birthday: "",
   position: "Программист 1С",
   avatar: nil,
   department: ""},
  {first_name: "Алексей",
   last_name: "Гордиенко",
   patronymic: "",
   mobile_phone1: "",
   mobile_phone2: "",
   ip_phone: "",
   email: "",
   birthday: "",
   position: "",
   avatar: nil,
   department: ""},
  {first_name: "Юрий",
   last_name: "Лопаенко",
   patronymic: "Алесеевич",
   mobile_phone1: "380503288392",
   mobile_phone2: "",
   ip_phone: "",
   email: "laupay@mail.ru",
   birthday: "06.03.1968",
   position: "Директор",
   avatar: nil,
   department: ""}
])
