Employee.create!([
  {first_name: "Евгений", last_name: "Исайченко", patronymic: "Андреевич", mobile_phone1: "380992889884", mobile_phone2: "", ip_phone: "115", email: "admin@dolina.ua", birthday: "11.05.1985", position: "Системный администратор", avatar: "25950734.jpeg", department: "IT"},
  {first_name: "Вячеслав", last_name: "Сергиенко", patronymic: "Анатольевич", mobile_phone1: "380992959018", mobile_phone2: "", ip_phone: "116", email: "sva0709@rambler.ru", birthday: "", position: "Программист 1С", avatar: nil, department: ""},
  {first_name: "Алексей", last_name: "Гордиенко", patronymic: "", mobile_phone1: "", mobile_phone2: "", ip_phone: "", email: "", birthday: "", position: "", avatar: nil, department: ""},
  {first_name: "Юрий", last_name: "Лопаенко", patronymic: "Алесеевич", mobile_phone1: "", mobile_phone2: "", ip_phone: "", email: "", birthday: "", position: "", avatar: nil, department: ""},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Главный бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Заместитель главного бухгалтера по упр.учету", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Заместитель главного бухгалтера", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Заместитель главного бухгалтера", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Бухгалтер", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Экономист-аналитик", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Экономист", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Экономист по сбыту", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Юрист", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Юрист", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Секретарь", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Экономист по сбыту", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Экономист по сбыту", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Научный отдел/ спец по регистрации", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Научный отдел", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Специалист по снабжению", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Менеджер по персоналу", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Менеджер по персоналу", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Системный администратор", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Программист 1С", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Заведующий хозяйством", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Водитель-логист", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Водитель", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Водитель офиса", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Кладовщик", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Коммерческий директор", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Менеджер по маркетингу", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Менеджер по рекламе", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Дизайнер ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Дизайнер ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Интернет-маркетолог", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Менеджер ВЭД", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Менеджер ВЭД", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Начальник отдела продаж", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Начальника отдела  продаж МФ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП (МФ) по Центру", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП (мелкая фасовка) по Западу", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Рук. Восточного региона ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "РЭ  по агрономическому сопровождению", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Харьковской области", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Днепропетровской области", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  Днепр", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП поЗапорожской области ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по Луганской области ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по Донецкой области ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по Донецкой области ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по  Херсонской  обл.", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Руководитель Западного региона", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "РЭ по агрономическому сопровождению", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Житомир", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по Львовской обл.", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по Волынская обл. и Ровенская", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Винница", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Винница", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Ивано-Франковск ,  Тернополь", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Черновцы,  Хмельницкий", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "Руководитель Центр.  региона", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "РЭ по агрономическому сопровождению", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Полтавской обл.", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Полтавской обл.", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Сумской  обл. ", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Черкасской обл.", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Кировоградской обл.", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Чернигов", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП Киев", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по  Николаевской области", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП по Одесской области (Север) и Николаевской области (Север)", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: "ТП  по Одесской области", avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: nil, avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: nil, avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: nil, avatar: nil, department: nil},
  {first_name: nil, last_name: nil, patronymic: nil, mobile_phone1: nil, mobile_phone2: nil, ip_phone: nil, email: nil, birthday: nil, position: nil, avatar: nil, department: nil}
])
